version: "3"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8081:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./swagger/openapi.json:/openapi.json 
    
    environment:
      SWAGGER_JSON: /openapi.json

  swagger-nginx:
    image: nginx:mainline-alpine
    container_name: "swagger-nginx"
    ports:
      - "8084:8084"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
